### PR TITLE
User guide

### PR DESCRIPTION
**Pull request by hellodommy**
Hi guys, I've updated the user guide as per the Google Doc we did on Tuesday.

Please look through to see if there's anything to change. I feel that we are lacking some sort of parallel structure. You can preview it on my branch [here](https://github.com/hellodommy/main/blob/user-guide/docs/UserGuide.adoc).

Also, I am lacking screenshots for `training` and `undo` as they are not in the `master` branch yet.

### CODE REVIEW

**Comment by ChangUo79** [comment]
I think we will need to update some of the screenshots after merging shawn's pull request to update the calendar.

**Comment by hellodommy** [comment]
> I think we will need to update some of the screenshots after merging shawn's pull request to update the calendar.

@ChangUo79 which screenshots exactly?

**Comment by ChangUo79** [comment]
> 
> 
> > I think we will need to update some of the screenshots after merging shawn's pull request to update the calendar.
> 
> @ChangUo79 which screenshots exactly?

image
Those that is displaying the calendar because shawn's calendar is updated with the dates (eg: 1 to 31). I think it can be added at a later time once we have merged the PRs.

**Comment by shawnlsj97** [comment]
Hi Dom, please fix the checkstyle errors so that we can merge your pull request!

**Pull request merged**
